### ISSUE TITLE
Ask about python

### ISSUE THREAD

**Issue by ThanhPham1987** [YaN9-Y/lafin#1]
Hi lafin,
Can i use python 3.6 for this code?
Best regards,
PeterPham

**Comment by YaN9-Y** [comment]
> Hi lafin,
> Can i use python 3.6 for this code?
> Best regards,
> PeterPham

Hi ThanhPhan1987,
My environment is Python3.7 but I think it would also be fine on Python3.6 as long as you can install the required dependencies successfully.
