### ISSUE TITLE
i get error when test model

### ISSUE THREAD

**Issue by redaghanem** [YaN9-Y/lafin#4]
thanks for sharing your code
i use google colab and when i type this line to test model
 
!python test.py --model 2 --checkpoints checkpoints/celeba_models

i get this result 

Loading InpaintingModel generator...

start testing...

End Testing

-----------

but folder result is empty

i use this config.yml

[config.zip](https://github.com/YaN9-Y/lafin/files/4112865/config.zip)

please help me

**Comment by YaN9-Y** [comment]
Please check the paths of filelist in your config file and try to save the file lists in a path without whitespaces.

**Comment by redaghanem** [comment]
thanks for reply

i think it's worked after use this

!python test.py --model 3 --checkpoints checkpoints/celeba_models  --output checkpoints/results


why 3 make inpainting test i understand from the documentation is 2 for inpainting test


Loading landmark detector...
Loading landmark detector complete!
Loading InpaintingModel generator...

start testing...

checkpoints/results/landmark_inpaint/joint/195579.png
checkpoints/results/landmark_inpaint/joint/196278.png
checkpoints/results/landmark_inpaint/joint/196680.png
checkpoints/results/landmark_inpaint/joint/200280.png
checkpoints/results/landmark_inpaint/joint/200281.png
checkpoints/results/landmark_inpaint/joint/200282.png
checkpoints/results/landmark_inpaint/joint/200283.png
checkpoints/results/landmark_inpaint/joint/200284.png

End Testing

**Comment by YaN9-Y** [comment]
--model 2: use ground truth landmarks to give inpaint result
--model 3: use predicted landmarks to give inpaint result
Hope this can help you!

**Comment by redaghanem** [comment]
Thanks 

Can i ask why when i use model 2 with all same files i get this error above the is there is a fill missing

**Comment by YaN9-Y** [comment]
Model 2 needs to generate ground truth landmark files first, if the landmark files don't exist, the error will be reported.  To generate the landmark files, you can see readme for detail.
Model 3 can predict landmarks, so it doesn't require landmark files.
